language:
  - objective-c

env:
    # global: LATEST_TAG=1
  matrix:
    - VERSION=2.7.8
    - VERSION=3.2.5
    - VERSION=3.3.5
    - VERSION=3.4.1

install:
    - source run_install.sh
    - get_python_environment macpython $VERSION venv
    - pip install delocate
    - if [ -n "$LATEST_TAG" ]; then checkout_closest_tag Pillow; fi
    - cd Pillow
    - python setup.py bdist_wheel
    - delocate-wheel dist/*.whl
    - rename_wheels dist/*.whl
    - pip install dist/*.whl
    - cd ..

script:
    - cd Pillow
    - python selftest.py --installed
    - pip install nose
    - export NOSE_PROCESS_TIMEOUT=600
    - export NOSE_PROCESSES=-1
    - if [ -f test-installed.py ]; then
      python test-installed.py ;
      else
      python Tests/run.py --installed ;
      fi
    - cd ..

before_deploy: cd Pillow/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: H5vKIC7VJVpenWsqimYUtCLrC+W0AECxDPDN+EmHa5tsz8uqJEpXB3xsSfJq6qvFBffhjQNKoetG8s5QtrXJYVquxOyiZKTYNx8/9nnQusXDPMmFoW3UR7hcSduiRMpygOH7/9VUD123jjE/qp4EyoKVEaqeArNEx5sSJO5LZvA=
  region: ORD
  container: wheels
  skip_cleanup: true
